# promise
## 1. 什么是promise?
Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6 将其写进了语言标准，统一了用法，原生提供了Promise对象。
## 2. promise使用
```javascript
const promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```
**Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个函数**
Promise使用过程，我们可以将它划分成三个状态：
- 待定（pending）: 初始状态，既没有被兑现，也没有被拒绝； 当执行executor中的代码时，处于该状态； 
- 已兑现（fulfilled）: 意味着操作成功完成； 执行了resolve时，处于该状态； 
- 已拒绝（rejected）: 意味着操作失败； 执行了reject时，处于该状态
**注意**
1. 新建promise后，里面的回调函数会被立即执行。
2. promise中的状态确定后不可更改，确定为resolve后reject不会执行。
## 3. resolve不同值的表现。
1. resolve一个普通值或对象，那么它会作为then回调的参数。
2. resolve一个新的promise，那么这个新的promise的状态会改变原promise的状态。
3. resolve中传入的是一个对象，并且这个对象有实现then方法，那么会执行该then方法，并且根据
   then方法的结果来决定Promise的状态：
## 4.then方法
1. then方法是放在Promise原型上的方法.
2. then方法接收两个参数，fulfilled和rejected的回调函数。
3. then方法可以被多次调用。
4. then方法有返回值，返回值是一个promise.
**then方法返回的promise有三种状态**
- 当then方法中的回调函数本身在执行的时候，那么它处于pending状态； 
- 当then方法中的回调函数返回一个结果时，那么它处于fulfilled状态，并且会将结果作为resolve的参数； 
  - 情况一：返回一个普通的值； 
  - 情况二：返回一个Promise； 
  - 情况三：返回一个thenable值； 
- 当then方法抛出一个异常时，那么它处于reject状态；
## 5. catch方法
1. catch方法是放在Promise原型上的方法.
2. catch方法可以被多次调用。
3. then方法有返回值，返回值是一个promise。
## 6. finally方法
1. 无论Promise对象无论变成fulfilled还是reject状态，最终都会被执行的代码。 
2. finally方法是不接收参数的，因为无论前面是fulfilled状态，还是reject状态，它都会执行。
## 7. 类方法
### 7.1 转换内容为promise对象
**用法相当于new Promise，并且执行resolve操作**
1. Promise.resolve
2. Promise.reject
### 7.2 all方法
- 将多个Promise包裹在一起形成一个新的Promise，参数为要包裹的promise数组。
- 新的Promise状态由包裹的所有Promise共同决定。
  - 当所有的Promise状态变成fulfilled状态时，新的Promise状态为fulfilled，并且会将所有Promise的返回值
    组成一个数组。
  - 当有一个Promise状态为reject时，新的Promise状态为reject，并且会将第一个reject的返回值作为参数。
### 7.3 allSettled方法
- 会在所有的Promise都有结果（settled），无论是fulfilled，还是reject时，才会有最终的状态。
- 这个Promise的结果一定是fulfilled的。
### 7.4 race方法
- 如果有一个Promise有了结果，我们就希望决定最终新Promise的状态，那么可以使用race方法。
### 7.5 any方法
- any方法会等到一个fulfilled状态，才会决定新Promise的状态。
- 如果所有的Promise都是reject的，那么也会等到所有的Promise都变成rejected状态。
- 如果所有的Promise都是reject的，那么会报一个AggregateError的错误。